# Generated by Django 4.2.3 on 2023-07-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_username',
            field=models.CharField(default='default_username', max_length=150),
        ),
    ]
